#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : docbook2X
Version  : 0.8.8
Release  : 6
URL      : https://sourceforge.net/projects/docbook2x/files/docbook2x/0.8.8/docbook2X-0.8.8.tar.gz
Source0  : https://sourceforge.net/projects/docbook2x/files/docbook2x/0.8.8/docbook2X-0.8.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: docbook2X-bin = %{version}-%{release}
Requires: docbook2X-data = %{version}-%{release}
Requires: docbook2X-info = %{version}-%{release}
Requires: docbook2X-license = %{version}-%{release}
Requires: docbook2X-man = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : groff
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::NamespaceSupport)
BuildRequires : perl(XML::SAX::Exception)
BuildRequires : perl(XML::SAX::ParserFactory)
BuildRequires : texinfo

%description
================
docbook2X converts DocBook documents into man pages and Texinfo
documents.

%package bin
Summary: bin components for the docbook2X package.
Group: Binaries
Requires: docbook2X-data = %{version}-%{release}
Requires: docbook2X-license = %{version}-%{release}

%description bin
bin components for the docbook2X package.


%package data
Summary: data components for the docbook2X package.
Group: Data

%description data
data components for the docbook2X package.


%package doc
Summary: doc components for the docbook2X package.
Group: Documentation
Requires: docbook2X-man = %{version}-%{release}
Requires: docbook2X-info = %{version}-%{release}

%description doc
doc components for the docbook2X package.


%package info
Summary: info components for the docbook2X package.
Group: Default

%description info
info components for the docbook2X package.


%package license
Summary: license components for the docbook2X package.
Group: Default

%description license
license components for the docbook2X package.


%package man
Summary: man components for the docbook2X package.
Group: Default

%description man
man components for the docbook2X package.


%prep
%setup -q -n docbook2X-0.8.8
cd %{_builddir}/docbook2X-0.8.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619059573
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1619059573
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/docbook2X
cp %{_builddir}/docbook2X-0.8.8/COPYING %{buildroot}/usr/share/package-licenses/docbook2X/920a513690cafc40211a7a9c74df580d329c126b
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/docbook2man
rm -f %{buildroot}/usr/bin/docbook2texi
rm -f %{buildroot}/usr/share/man/man1/docbook2texi.1
rm -f %{buildroot}/usr/share/man/man1/docbook2man.1

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/db2x_manxml
/usr/bin/db2x_texixml
/usr/bin/db2x_xsltproc
/usr/bin/sgml2xml-isoent
/usr/bin/utf8trans

%files data
%defattr(-,root,root,-)
/usr/share/docbook2X/VERSION
/usr/share/docbook2X/charmaps/roff-small.charmap.xml
/usr/share/docbook2X/charmaps/roff.charmap
/usr/share/docbook2X/charmaps/roff.charmap.xml
/usr/share/docbook2X/charmaps/texi-small.charmap.xml
/usr/share/docbook2X/charmaps/texi.charmap
/usr/share/docbook2X/charmaps/texi.charmap.xml
/usr/share/docbook2X/dtd/Man-XML
/usr/share/docbook2X/dtd/Texi-XML
/usr/share/docbook2X/dtd/catalog.xml
/usr/share/docbook2X/xslt/backend/charmap.xsl
/usr/share/docbook2X/xslt/backend/db2x_manxml.xsl
/usr/share/docbook2X/xslt/backend/db2x_texixml.xsl
/usr/share/docbook2X/xslt/backend/man-html-table.xsl
/usr/share/docbook2X/xslt/backend/man-table.xsl
/usr/share/docbook2X/xslt/backend/string.xsl
/usr/share/docbook2X/xslt/catalog.xml
/usr/share/docbook2X/xslt/common/check-idref.xsl
/usr/share/docbook2X/xslt/common/cmdsynopsis.xsl
/usr/share/docbook2X/xslt/common/gentext.xsl
/usr/share/docbook2X/xslt/common/l10n.xsl
/usr/share/docbook2X/xslt/common/labels.xsl
/usr/share/docbook2X/xslt/common/lists.xsl
/usr/share/docbook2X/xslt/common/messages.xsl
/usr/share/docbook2X/xslt/common/person.xsl
/usr/share/docbook2X/xslt/common/string.xsl
/usr/share/docbook2X/xslt/common/text/af.xml
/usr/share/docbook2X/xslt/common/text/bg.xml
/usr/share/docbook2X/xslt/common/text/ca.xml
/usr/share/docbook2X/xslt/common/text/cs.xml
/usr/share/docbook2X/xslt/common/text/da.xml
/usr/share/docbook2X/xslt/common/text/de.xml
/usr/share/docbook2X/xslt/common/text/el.xml
/usr/share/docbook2X/xslt/common/text/en.xml
/usr/share/docbook2X/xslt/common/text/es.xml
/usr/share/docbook2X/xslt/common/text/et.xml
/usr/share/docbook2X/xslt/common/text/eu.xml
/usr/share/docbook2X/xslt/common/text/fi.xml
/usr/share/docbook2X/xslt/common/text/fr.xml
/usr/share/docbook2X/xslt/common/text/he.xml
/usr/share/docbook2X/xslt/common/text/hu.xml
/usr/share/docbook2X/xslt/common/text/id.xml
/usr/share/docbook2X/xslt/common/text/it.xml
/usr/share/docbook2X/xslt/common/text/ja.xml
/usr/share/docbook2X/xslt/common/text/ko.xml
/usr/share/docbook2X/xslt/common/text/l10n-set.xml
/usr/share/docbook2X/xslt/common/text/lt.xml
/usr/share/docbook2X/xslt/common/text/nl.xml
/usr/share/docbook2X/xslt/common/text/nn.xml
/usr/share/docbook2X/xslt/common/text/no.xml
/usr/share/docbook2X/xslt/common/text/pl.xml
/usr/share/docbook2X/xslt/common/text/pt-br.xml
/usr/share/docbook2X/xslt/common/text/pt.xml
/usr/share/docbook2X/xslt/common/text/ro.xml
/usr/share/docbook2X/xslt/common/text/ru.xml
/usr/share/docbook2X/xslt/common/text/sk.xml
/usr/share/docbook2X/xslt/common/text/sl.xml
/usr/share/docbook2X/xslt/common/text/sr.xml
/usr/share/docbook2X/xslt/common/text/sv.xml
/usr/share/docbook2X/xslt/common/text/th.xml
/usr/share/docbook2X/xslt/common/text/tr.xml
/usr/share/docbook2X/xslt/common/text/uk.xml
/usr/share/docbook2X/xslt/common/text/vi.xml
/usr/share/docbook2X/xslt/common/text/xh.xml
/usr/share/docbook2X/xslt/common/text/zh-cn.xml
/usr/share/docbook2X/xslt/common/text/zh-tw.xml
/usr/share/docbook2X/xslt/common/titles.xsl
/usr/share/docbook2X/xslt/common/ucase.xsl
/usr/share/docbook2X/xslt/common/version.xsl
/usr/share/docbook2X/xslt/common/whitespace.xsl
/usr/share/docbook2X/xslt/man/admon.xsl
/usr/share/docbook2X/xslt/man/beginpage.xsl
/usr/share/docbook2X/xslt/man/block.xsl
/usr/share/docbook2X/xslt/man/caption.xsl
/usr/share/docbook2X/xslt/man/docbook.xsl
/usr/share/docbook2X/xslt/man/formal.xsl
/usr/share/docbook2X/xslt/man/glossary.xsl
/usr/share/docbook2X/xslt/man/index.xsl
/usr/share/docbook2X/xslt/man/info.xsl
/usr/share/docbook2X/xslt/man/inline.xsl
/usr/share/docbook2X/xslt/man/keywords.xsl
/usr/share/docbook2X/xslt/man/lists.xsl
/usr/share/docbook2X/xslt/man/manpage.xsl
/usr/share/docbook2X/xslt/man/param.xsl
/usr/share/docbook2X/xslt/man/pi.xsl
/usr/share/docbook2X/xslt/man/refentry.xsl
/usr/share/docbook2X/xslt/man/sectioning.xsl
/usr/share/docbook2X/xslt/man/sections.xsl
/usr/share/docbook2X/xslt/man/synop.xsl
/usr/share/docbook2X/xslt/man/table.xsl
/usr/share/docbook2X/xslt/man/toc.xsl
/usr/share/docbook2X/xslt/man/verbatim.xsl
/usr/share/docbook2X/xslt/man/xref.xsl
/usr/share/docbook2X/xslt/texi/admon.xsl
/usr/share/docbook2X/xslt/texi/autotoc.xsl
/usr/share/docbook2X/xslt/texi/beginpage.xsl
/usr/share/docbook2X/xslt/texi/biblio.xsl
/usr/share/docbook2X/xslt/texi/block.xsl
/usr/share/docbook2X/xslt/texi/callout.xsl
/usr/share/docbook2X/xslt/texi/caption.xsl
/usr/share/docbook2X/xslt/texi/chunk.xsl
/usr/share/docbook2X/xslt/texi/component.xsl
/usr/share/docbook2X/xslt/texi/division.xsl
/usr/share/docbook2X/xslt/texi/docbook.xsl
/usr/share/docbook2X/xslt/texi/footnote.xsl
/usr/share/docbook2X/xslt/texi/force-inline.xsl
/usr/share/docbook2X/xslt/texi/formal.xsl
/usr/share/docbook2X/xslt/texi/glossary.xsl
/usr/share/docbook2X/xslt/texi/graphics.xsl
/usr/share/docbook2X/xslt/texi/index.xsl
/usr/share/docbook2X/xslt/texi/info.xsl
/usr/share/docbook2X/xslt/texi/inline.xsl
/usr/share/docbook2X/xslt/texi/jrefentry.xsl
/usr/share/docbook2X/xslt/texi/keywords.xsl
/usr/share/docbook2X/xslt/texi/lists.xsl
/usr/share/docbook2X/xslt/texi/math.xsl
/usr/share/docbook2X/xslt/texi/menudescrip.xsl
/usr/share/docbook2X/xslt/texi/param.xsl
/usr/share/docbook2X/xslt/texi/pi.xsl
/usr/share/docbook2X/xslt/texi/qandaset.xsl
/usr/share/docbook2X/xslt/texi/refentry.xsl
/usr/share/docbook2X/xslt/texi/sectioning.xsl
/usr/share/docbook2X/xslt/texi/sections.xsl
/usr/share/docbook2X/xslt/texi/synop.xsl
/usr/share/docbook2X/xslt/texi/table.xsl
/usr/share/docbook2X/xslt/texi/texifile.xsl
/usr/share/docbook2X/xslt/texi/texinode-base.xsl
/usr/share/docbook2X/xslt/texi/texinode.xsl
/usr/share/docbook2X/xslt/texi/toc.xsl
/usr/share/docbook2X/xslt/texi/verbatim.xsl
/usr/share/docbook2X/xslt/texi/xref.xsl

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/docbook2X/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/docbook2X.info
/usr/share/info/docbook2man-xslt.info
/usr/share/info/docbook2texi-xslt.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/docbook2X/920a513690cafc40211a7a9c74df580d329c126b

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/db2x_manxml.1
/usr/share/man/man1/db2x_texixml.1
/usr/share/man/man1/db2x_xsltproc.1
/usr/share/man/man1/sgml2xml-isoent.1
/usr/share/man/man1/utf8trans.1
